version: "3.7"
services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
  #   restart: always
  #   environment:
  #     # - "network.bind_host=0"
  #     # - "network.host=0.0.0.0"
  #     - http.host=0.0.0.0
  #     - transport.host=localhost
  #     - network.host=0.0.0.0
  #     - "bootstrap.memory_lock=true"
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.type=single-node"
  #   # volumes:
  #   #   - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #   ports: # Expose Elasticsearch ports
  #     - "9300:9300"
  #     - "9201:9200"
  #     - "9202:9200"
  #     - "9200:9200"
  #   networks:
  #     - esnet
  mysql:
    image: mysql:5.6.40
    restart: always
    environment:
      MYSQL_DATABASE: 'cepheid_test'
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - mysql_data/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    networks: ['esnet']
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
    #   # Where our data will be persisted
  # ruby:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - elasticsearch
  #     - mysql
  #   networks: ['esnet']
networks:
  esnet:
volumes:
  mysql_data