version: "3.7"
services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6.40
    #restart: always
    environment:
      MYSQL_DATABASE: 'cepheid_test'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  