version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    restart: always
    ports:
      - '9200:9200'
    networks:
      - esnet
  mysql:
    image: mysql:5.6.40
    restart: always
    environment:
      MYSQL_DATABASE: 'cepheid_test'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    depends_on:
      - elasticsearch
    networks: ['esnet']
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
    #   # Where our data will be persisted
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks: ['esnet']
networks:
  esnet: